# Generated by Django 3.2.1 on 2021-05-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAttributeSimilarityValidator',
            new_name='User',
        ),
    ]
